---
abstract: 'utilities for generating C programs'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: C-Utility
no_index:
  directory:
    - t
    - inc
requires:
  File::Versions: 0
  perl: 5.006001
resources:
  bugtracker: https://github.com/benkasminbullock/C-Utility/issues
  repository: https://github.com/benkasminbullock/C-Utility
version: 0.004
